services:
  nginx:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data/nginx:/data
      - ./data/letsencrypt:/etc/letsencrypt
    networks:
      - syncvela-network

  backend:
    build:
      context: ./backend
    container_name: syncvela-backend
    env_file:
      - ./backend/.env
    networks:
      - syncvela-network

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL="https://syncvela.codes"
        - NEXT_PUBLIC_GOOGLE_CLIENT_ID="156382073736-dk5fb09ggkklglnhnqcsmed7b3npjgv9.apps.googleusercontent.com"
    container_name: syncvela-frontend
    env_file:
      - ./frontend/.env
    networks:
      - syncvela-network

networks:
  syncvela-network:
    driver: bridge