services:
  nginx:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data/nginx:/data
      - ./data/letsencrypt:/etc/letsencrypt
    networks:
      - syncvela-network

  backend:
    image: ${DOCKER_USERNAME}/syncvela-backend:latest
    container_name: syncvela-backend-prod
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - syncvela-network

  frontend:
    image: ${DOCKER_USERNAME}/syncvela-frontend:latest
    container_name: syncvela-frontend-prod
    restart: unless-stopped
    networks:
      - syncvela-network

networks:
  syncvela-network:
    driver: bridge
